OOF.Microstructure.Create_From_ImageFile(filename='/Users/langer/FE/MAN_OOF2/FIGURESOURCES/swoops.png', microstructure_name='swoops.png', height=1, width=automatic)
OOF.Windows.Graphics.New()
OOF.Graphics_1.Layer.Select(n=0)
OOF.Graphics_1.Layer.Select(n=0)
OOF.Graphics_1.Layer.Select(n=0)
OOF.PixelGroup.AutoGroup(grouper=ColorGrouper(image='swoops.png:swoops.png',sigma0=0.002), delta=1, gamma=2, minsize=100, contiguous=True, name_template='group_%n', clear=False)
OOF.PixelSelection.Select_Group(microstructure='swoops.png', group='group_3')
OOF.PixelSelection.Select_Group(microstructure='swoops.png', group='group_4')
OOF.PixelSelection.Select_Group(microstructure='swoops.png', group='group_2')
OOF.PixelSelection.Select_Group(microstructure='swoops.png', group='group_1')
OOF.Material.New(name='matrix', material_type='bulk')
OOF.Material.Assign(material='matrix', microstructure='swoops.png', pixels=selection)
OOF.PixelSelection.Invert(microstructure='swoops.png')
OOF.Material.New(name='grains', material_type='bulk')
OOF.Material.Assign(material='grains', microstructure='swoops.png', pixels=selection)
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic', new_name='hgh')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.hgh(kappa=5)
OOF.Material.Add_property(name='matrix', property='Thermal:Conductivity:Isotropic:hgh')
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic:hgh', new_name='low')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.low(kappa=1)
OOF.Material.Add_property(name='grains', property='Thermal:Conductivity:Isotropic:low')
OOF.Material.Add_property(name='grains', property='Thermal:HeatCapacity:ConstantHeatCapacity')
OOF.Material.Add_property(name='matrix', property='Thermal:HeatCapacity:ConstantHeatCapacity')
OOF.Skeleton.New(name='skeleton', microstructure='swoops.png', x_elements=4, y_elements=4, skeleton_geometry=QuadSkeleton(left_right_periodicity=False,top_bottom_periodicity=False))
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Refine(targets=CheckHomogeneity(threshold=0.9),divider=Bisection(minlength=0),rules='Quick',alpha=0.8))
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Refine(targets=CheckHomogeneity(threshold=0.9),divider=Bisection(minlength=0),rules='Quick',alpha=0.8))
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Refine(targets=CheckHomogeneity(threshold=0.9),divider=Bisection(minlength=0),rules='Quick',alpha=0.8))
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Refine(targets=CheckHomogeneity(threshold=0.9),divider=TransitionPoints(minlength=0.1),rules='Quick',alpha=0.8))
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Rationalize(targets=AllElements(),criterion=AverageEnergy(alpha=0.8),method=SpecificRationalization(rationalizers=[RemoveShortSide(ratio=5.0), QuadSplit(angle=150), RemoveBadTriangle(acute_angle=15,obtuse_angle=150)]),iterations=2))
OOF.Skeleton.PinNodes.Pin_Internal_Boundary_Nodes(skeleton='swoops.png:skeleton')
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Smooth(targets=AllNodes(),criterion=AverageEnergy(alpha=0.3),T=0.0,iteration=FixedIteration(iterations=5)))
OOF.Skeleton.PinNodes.Undo(skeleton='swoops.png:skeleton')
OOF.Mesh.New(name='mesh', skeleton='swoops.png:skeleton', element_types=['D2_3', 'T3_6', 'Q4_8'])
OOF.Subproblem.Field.Define(subproblem='swoops.png:skeleton:mesh:default', field=Temperature)
OOF.Subproblem.Field.Activate(subproblem='swoops.png:skeleton:mesh:default', field=Temperature)
OOF.Mesh.Field.In_Plane(mesh='swoops.png:skeleton:mesh', field=Temperature)
OOF.Subproblem.Equation.Activate(subproblem='swoops.png:skeleton:mesh:default', equation=Heat_Eqn)
OOF.Mesh.Boundary_Conditions.New(name='bc', mesh='swoops.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=0),boundary='left'))
OOF.Mesh.Boundary_Conditions.New(name='bc<2>', mesh='swoops.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ContinuumProfileXTd(function='min(1, t)',timeDerivative='1 if t<1 else 0',timeDerivative2='0.0'),boundary='right'))
OOF.Mesh.Scheduled_Output.New(mesh='swoops.png:skeleton:mesh', name=AutomaticName('GraphicsUpdate'), output=GraphicsUpdate())
OOF.Mesh.Scheduled_Output.Schedule.Set(mesh='swoops.png:skeleton:mesh', output=AutomaticName('GraphicsUpdate'), scheduletype=AbsoluteOutputSchedule(), schedule=Periodic(delay=0,interval=0.05))
OOF.Subproblem.Set_Solver(subproblem='swoops.png:skeleton:mesh:default', solver_mode=BasicSolverMode(time_stepper=BasicAdaptiveDriver(tolerance=0.0001,minstep=1e-05),matrix_method=BasicIterative(tolerance=1e-13,max_iterations=10000)))
OOF.Mesh.Set_Field_Initializer(mesh='swoops.png:skeleton:mesh', field=Temperature, initializer=ConstScalarFieldInit(value=0))
OOF.Mesh.Scheduled_Output.New(mesh='swoops.png:skeleton:mesh', name='GraphicsUpdate<2>', output=GraphicsUpdate())
OOF.Mesh.Scheduled_Output.Schedule.Set(mesh='swoops.png:skeleton:mesh', output='GraphicsUpdate<2>', scheduletype=AbsoluteOutputSchedule(), schedule=Periodic(delay=0,interval=0.05))
OOF.Mesh.Scheduled_Output.Delete(mesh='swoops.png:skeleton:mesh', output='GraphicsUpdate<2>')
OOF.Graphics_1.Layer.New(category='Mesh', what='swoops.png:skeleton:mesh', how=FilledContourDisplay(when=latest,what=getOutput('Field:Component',component='',field=Temperature),where=getOutput('original'),min=automatic,max=automatic,levels=21,nbins=5,colormap=ThermalMap()))
OOF.Graphics_1.Toolbox.Pixel_Select.Clear(source='swoops.png:swoops.png')
OOF.Subproblem.Set_Solver(subproblem='swoops.png:skeleton:mesh:default', solver_mode=AdvancedSolverMode(time_stepper=UniformDriver(stepper=CrankNicolson(),stepsize=0.01),nonlinear_solver=NoNonlinearSolver(),symmetric_solver=ConjugateGradient(preconditioner=ICPreconditioner(),tolerance=1e-13,max_iterations=10000),asymmetric_solver=StabilizedBiConjugateGradient(preconditioner=ICPreconditioner(),tolerance=1e-13,max_iterations=1000)))
OOF.Mesh.Set_Field_Initializer(mesh='swoops.png:skeleton:mesh', field=Temperature, initializer=ConstScalarFieldInit(value=0))
OOF.Mesh.Solve(mesh='swoops.png:skeleton:mesh', endtime=1.0)
OOF.Graphics_1.Layer.Hide(n=5)
OOF.Graphics_1.Layer.Select(n=5)
OOF.Graphics_1.Layer.Hide(n=6)
OOF.Graphics_1.Layer.Select(n=6)
OOF.Graphics_1.Settings.Antialias(0)
OOF.Graphics_1.Settings.Antialias(1)
OOF.Mesh.New(name='mesh2', skeleton='swoops.png:skeleton', element_types=['D2_2', 'T3_3', 'Q4_4'])
OOF.Subproblem.Copy_Field_State(source='swoops.png:skeleton:mesh:default', target='swoops.png:skeleton:mesh2:default')
OOF.Subproblem.Copy_Equation_State(source='swoops.png:skeleton:mesh:default', target='swoops.png:skeleton:mesh2:default')
OOF.Mesh.Boundary_Conditions.Copy_All(current='swoops.png:skeleton:mesh', mesh='swoops.png:skeleton:mesh2')
OOF.Mesh.Boundary_Conditions.Edit(name='bc<2>', mesh='swoops.png:skeleton:mesh2', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ContinuumProfileXTd(function='0.5*min(2, t)',timeDerivative='0.5 if t<2 else 0',timeDerivative2='0.0'),boundary='right'))
OOF.Mesh.Scheduled_Output.New(mesh='swoops.png:skeleton:mesh2', name='GraphicsUpdate<2>', output=GraphicsUpdate())
OOF.Mesh.Scheduled_Output.Schedule.Set(mesh='swoops.png:skeleton:mesh2', output='GraphicsUpdate<2>', scheduletype=AbsoluteOutputSchedule(), schedule=Periodic(delay=0,interval=0.1))
OOF.Mesh.Copy_All_Solvers(source='swoops.png:skeleton:mesh', target='swoops.png:skeleton:mesh2')
OOF.Mesh.Set_Field_Initializer(mesh='swoops.png:skeleton:mesh2', field=Temperature, initializer=ConstScalarFieldInit(value=0))
OOF.Mesh.Apply_Field_Initializers_at_Time(mesh='swoops.png:skeleton:mesh2', time=0)
OOF.Graphics_1.Layer.Select(n=1)
OOF.Graphics_1.Layer.Edit(n=1, category='Mesh', what='swoops.png:skeleton:mesh', how=FilledContourDisplay(when=latest,what=getOutput('Field:Component',component='',field=Temperature),where=getOutput('original'),min=automatic,max=automatic,levels=21,nbins=5,colormap=ThermalMap()))
OOF.Mesh.Apply_Field_Initializers_at_Time(mesh='swoops.png:skeleton:mesh', time=0)
OOF.Mesh.Solve(mesh='swoops.png:skeleton:mesh', endtime=1.0)
#OOF.Mesh.Apply_Field_Initializers_at_Time(mesh='swoops.png:skeleton:mesh2', time=0)
#OOF.Graphics_1.Settings.Time(time=0.005128205128205128)
#OOF.Graphics_1.Settings.Time(time=0.02564102564102564)
#OOF.Graphics_1.Settings.Time(time=0.06153846153846154)
#OOF.Graphics_1.Settings.Time(time=0.2564102564102564)
#OOF.Graphics_1.Settings.Time(time=0.26153846153846155)
#OOF.Graphics_1.Settings.Time(time=0.26666666666666666)
#OOF.Graphics_1.Settings.Time(time=0.28205128205128205)
#OOF.Graphics_1.Settings.Time(time=0.2923076923076923)
#OOF.Graphics_1.Settings.Time(time=0.29743589743589743)
#OOF.Graphics_1.Settings.Time(time=0.30256410256410254)
#OOF.Graphics_1.Settings.Time(time=0.3076923076923077)
#OOF.Graphics_1.Settings.Time(time=0.31794871794871793)
#OOF.Graphics_1.Settings.Time(time=0.3435897435897436)
#OOF.Graphics_1.Settings.Time(time=0.3641025641025641)
#OOF.Graphics_1.Settings.Time(time=0.38461538461538464)
#OOF.Graphics_1.Settings.Time(time=0.41025641025641024)
#OOF.Graphics_1.Settings.Time(time=0.4256410256410256)
#OOF.Graphics_1.Settings.Time(time=0.4307692307692308)
#OOF.Graphics_1.Settings.Time(time=0.4358974358974359)
#OOF.Graphics_1.Settings.Time(time=0.4461538461538462)
#OOF.Graphics_1.Settings.Time(time=0.4512820512820513)
#OOF.Graphics_1.Settings.Time(time=0.4564102564102564)
#OOF.Graphics_1.Settings.Time(time=0.46153846153846156)
