OOF.Microstructure.Create_From_ImageFile(filename='/Users/langer/FE/MAN_OOF2/FIGURESOURCES/swoops.png', microstructure_name='swoops.png', height=1, width=automatic)
OOF.Windows.Graphics.New()
OOF.Graphics_1.Layer.Select(n=0)
OOF.Graphics_1.Layer.Select(n=0)
OOF.PixelGroup.AutoGroup(grouper=ColorGrouper(image='swoops.png:swoops.png',sigma0=0.002), delta=1, gamma=2, minsize=100, contiguous=True, name_template='group_%n', clear=False)
OOF.PixelSelection.Select_Group(microstructure='swoops.png', group='group_3')
OOF.PixelSelection.Select_Group(microstructure='swoops.png', group='group_4')
OOF.PixelSelection.Select_Group(microstructure='swoops.png', group='group_2')
OOF.PixelSelection.Select_Group(microstructure='swoops.png', group='group_1')
OOF.Material.New(name='matrix', material_type='bulk')
OOF.Material.Assign(material='matrix', microstructure='swoops.png', pixels=selection)
OOF.PixelSelection.Invert(microstructure='swoops.png')
OOF.Material.New(name='grains', material_type='bulk')
OOF.Material.Assign(material='grains', microstructure='swoops.png', pixels=selection)
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic', new_name='hgh')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.hgh(kappa=5)
OOF.Material.Add_property(name='matrix', property='Thermal:Conductivity:Isotropic:hgh')
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic:hgh', new_name='low')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.low(kappa=1)
OOF.Material.Add_property(name='grains', property='Thermal:Conductivity:Isotropic:low')
OOF.Material.Add_property(name='grains', property='Thermal:HeatCapacity:ConstantHeatCapacity')
OOF.Material.Add_property(name='matrix', property='Thermal:HeatCapacity:ConstantHeatCapacity')
OOF.Skeleton.New(name='skeleton', microstructure='swoops.png', x_elements=4, y_elements=4, skeleton_geometry=QuadSkeleton(left_right_periodicity=False,top_bottom_periodicity=False))
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Refine(targets=CheckHomogeneity(threshold=0.9),divider=Bisection(minlength=0),rules='Quick',alpha=0.8))
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Refine(targets=CheckHomogeneity(threshold=0.9),divider=Bisection(minlength=0),rules='Quick',alpha=0.8))
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Refine(targets=CheckHomogeneity(threshold=0.9),divider=Bisection(minlength=0),rules='Quick',alpha=0.8))
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Refine(targets=CheckHomogeneity(threshold=0.9),divider=TransitionPoints(minlength=0.1),rules='Quick',alpha=0.8))
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Rationalize(targets=AllElements(),criterion=AverageEnergy(alpha=0.8),method=SpecificRationalization(rationalizers=[RemoveShortSide(ratio=5.0), QuadSplit(angle=150), RemoveBadTriangle(acute_angle=15,obtuse_angle=150)]),iterations=2))
OOF.Skeleton.PinNodes.Pin_Internal_Boundary_Nodes(skeleton='swoops.png:skeleton')
OOF.Skeleton.Modify(skeleton='swoops.png:skeleton', modifier=Smooth(targets=AllNodes(),criterion=AverageEnergy(alpha=0.3),T=0.0,iteration=FixedIteration(iterations=5)))
OOF.Skeleton.PinNodes.Undo(skeleton='swoops.png:skeleton')
OOF.Mesh.New(name='mesh', skeleton='swoops.png:skeleton', element_types=['D2_3', 'T3_6', 'Q4_8'])
OOF.Subproblem.Field.Define(subproblem='swoops.png:skeleton:mesh:default', field=Temperature)
OOF.Subproblem.Field.Activate(subproblem='swoops.png:skeleton:mesh:default', field=Temperature)
OOF.Mesh.Field.In_Plane(mesh='swoops.png:skeleton:mesh', field=Temperature)
OOF.Subproblem.Equation.Activate(subproblem='swoops.png:skeleton:mesh:default', equation=Heat_Eqn)
OOF.Mesh.Boundary_Conditions.New(name='bc', mesh='swoops.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=0),boundary='left'))
OOF.Mesh.Boundary_Conditions.New(name='bc<2>', mesh='swoops.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ContinuumProfileXTd(function='min(1, t)',timeDerivative='1 if t<1 else 0',timeDerivative2='0.0'),boundary='right'))
OOF.Mesh.Scheduled_Output.New(mesh='swoops.png:skeleton:mesh', name=AutomaticName('GraphicsUpdate'), output=GraphicsUpdate())
OOF.Mesh.Scheduled_Output.Schedule.Set(mesh='swoops.png:skeleton:mesh', output=AutomaticName('GraphicsUpdate'), scheduletype=AbsoluteOutputSchedule(), schedule=Periodic(delay=0,interval=0.05))
OOF.Subproblem.Set_Solver(subproblem='swoops.png:skeleton:mesh:default', solver_mode=BasicSolverMode(time_stepper=BasicAdaptiveDriver(tolerance=0.0001,minstep=1e-05),matrix_method=BasicIterative(tolerance=1e-13,max_iterations=10000)))
OOF.Mesh.Set_Field_Initializer(mesh='swoops.png:skeleton:mesh', field=Temperature, initializer=ConstScalarFieldInit(value=0))
OOF.Mesh.Scheduled_Output.New(mesh='swoops.png:skeleton:mesh', name='GraphicsUpdate<2>', output=GraphicsUpdate())
OOF.Mesh.Scheduled_Output.Schedule.Set(mesh='swoops.png:skeleton:mesh', output='GraphicsUpdate<2>', scheduletype=AbsoluteOutputSchedule(), schedule=Periodic(delay=0,interval=0.05))
OOF.Mesh.Scheduled_Output.Delete(mesh='swoops.png:skeleton:mesh', output='GraphicsUpdate<2>')
OOF.Graphics_1.Layer.New(category='Mesh', what='swoops.png:skeleton:mesh', how=FilledContourDisplay(when=latest,what=getOutput('Field:Component',component='',field=Temperature),where=getOutput('original'),min=automatic,max=automatic,levels=21,nbins=5,colormap=ThermalMap()))
OOF.Graphics_1.Toolbox.Pixel_Select.Clear(source='swoops.png:swoops.png')
